global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'notification-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['notification:4002']

  - job_name: 'email-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['email:4003']

  - job_name: 'sms-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['sms:4004']
